---
title: "README"
author: "Pablo Reyes Moctezua"
date: "7/12/2021"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Fiscal Measures in Response to the COVID-19 Pandemic

This repository contains a **clean, open format, and fully machine-readable** version of the IMF's database summarizing **key fiscal measures governments have announced or taken in selected economies in response to the COVID-19 pandemic** as of March 17, 2021.

In this repository, you can also find the R code and auxiliary data files used to clean and complement the [original dataset](https://www.imf.org/en/Topics/imf-and-covid19/Fiscal-Policies-Database-in-Response-to-COVID-19).

## Data source :books:

The original dataset is the [*Fiscal Monitor Database of Country Fiscal Measures in Response to the COVID-19 Pandemic*](https://www.imf.org/en/Topics/imf-and-covid19/Fiscal-Policies-Database-in-Response-to-COVID-19), prepared by the International Monetary Fund.

Additionally, three other datasets were used to complement the original data: The United Nations' [*Standard Country or Area Codes for Statistical Use*](https://unstats.un.org/unsd/methodology/m49/), the World Bank [*Country and Lending Groups*](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups) ---mainly, the country grouping into low, lower-middle, upper-middle, and high income economies---, and some key economic indicators retrieved from the World Bank [*Data Bank*](https://databank.bancomundial.org/) ---namely, Gini Index, GDP in current prices (US dollars), and share of population living below the $1.90, $3.20, and $5.50 poverty lines.

The additional data allows for some quick-and-dirty region and country comparisons. Plus, the inclusion of the UN's [*Standard Country or Area Codes for Statistical Use*](https://unstats.un.org/unsd/methodology/m49/) will allow you to easily merge this data with any other economic or socio-demographic set of indicators.

### A small warning on comparisons

The original dataset includes the following warning:

> The database is not meant for classifying the measures for fiscal reporting, **nor for comparison across economies as responses vary depending on country-specific circumstances...**

Despite this warning, the IMF report does includes some country-grouping and country-comparisons (:unamused:).

Anyway, be careful and always provide some context to your compared policy analysis.

## Repository contents

-   `Data`: Contains all raw data files used by the scripts contained in the repo.

    -   `Data/CLASS.xls`: [*Country and Lending Groups*](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups)(World Bank)*.*

    -   `Data/FMI-FiscalMeasures-Data.xlsx`: [*Fiscal Monitor Database of Country Fiscal Measures in Response to the COVID-19 Pandemic*](https://www.imf.org/en/Topics/imf-and-covid19/Fiscal-Policies-Database-in-Response-to-COVID-19)(IMF).

    -   `Data/UNSD_codes.csv`: [*Standard Country or Area Codes for Statistical Use*](https://unstats.un.org/unsd/methodology/m49/)(UN)*.*

    -   `Data/WorldBankData.csv`: Key economic indicators retrieved from the World Bank [*Data Bank*](https://databank.bancomundial.org/) ---namely, Gini Index, GDP in current prices (US dollars), and share of population living below the $1.90, $3.20, and $5.50 poverty lines.

-   `Out`: Contains all output generated by the scripts container in the repo.

    -   `Out/IMF_FiscalResponseData.*`: clean, open format, and fully machine-readable version of the IMF's database summarizing key fiscal measures governments have announced or taken in selected economies in response to the COVID-19 pandemic as of March 17, 2021. The dataset is available in both CSV and Rds formats.

-   `R`: Contains all R scripts.
